INSERT INTO country (name) VALUES ('India');
INSERT INTO country (name) VALUES ('Brazil');
INSERT INTO country (name) VALUES ('USA');
INSERT INTO country (name) VALUES ('Italy');
INSERT INTO country (name) VALUES ('Germany');
INSERT INTO country (name) VALUES ('France');
INSERT INTO country (name) VALUES ('England');
INSERT INTO country (name) VALUES ('Russia');
INSERT INTO country (name) VALUES ('China');
INSERT INTO country (name) VALUES ('Japan');
INSERT INTO country (name) VALUES ('Australia');
INSERT INTO country (name) VALUES ('New Zealand');
INSERT INTO country (name) VALUES ('South Africa');
INSERT INTO country (name) VALUES ('Sri Lanka');
INSERT INTO country (name) VALUES ('Bangladesh');
INSERT INTO country (name) VALUES ('Pakistan');
INSERT INTO country (name) VALUES ('Nepal');
INSERT INTO country (name) VALUES ('Bhutan');
INSERT INTO country (name) VALUES ('Afghanistan');
INSERT INTO country (name) VALUES ('Iran');
INSERT INTO country (name) VALUES ('Iraq');
INSERT INTO country (name) VALUES ('Saudi Arabia');
INSERT INTO country (name) VALUES ('UAE');
INSERT INTO country (name) VALUES ('Qatar');
INSERT INTO country (name) VALUES ('Oman');